name: iquranic

description: 'A Electronic Quran app that helps you to read, understand, and
  search the Quran. It also has a feature to listen to the Quran recitation.'

publish_to: 'none'

version: 1.5.6+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_facebook_auth: ^6.1.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  hijri: ^3.0.0
  http: ^1.1.0
  just_audio: ^0.9.36
  localstorage: ^4.0.1+4
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:

flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/images/logo-transparent.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/logo-transparent.png'
    theme_color: '#9543FF'
    background_color: '#FFFFFF'
